package com.com.sky.downloader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.myvideo.greenbean.Find;
import com.bawei.myvideo.greenbean.Person;
import com.bawei.myvideo.greenbean.User;

import com.com.sky.downloader.greendao.FindDao;
import com.com.sky.downloader.greendao.PersonDao;
import com.com.sky.downloader.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig findDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FindDao findDao;
    private final PersonDao personDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        findDaoConfig = daoConfigMap.get(FindDao.class).clone();
        findDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        findDao = new FindDao(findDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Find.class, findDao);
        registerDao(Person.class, personDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        findDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FindDao getFindDao() {
        return findDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
